package com.project.inventory_management_system.enums;

public enum OrderStatus
{

    // PROJECT TEAM
    PROJECT_TEAM_PENDING(
            "PROJECT TEAM PENDING"),
    PROJECT_TEAM_FINANCE_PRE_APPROVAL_PENDING(
            "PROJECT TEAM > FINANCE PRE APPROVAL PENDING"),
    PROJECT_TEAM_SCM_PENDING(
            "PROJECT TEAM > SCM PENDING"),
    PROJECT_TEAM_NOTIFY_AMISP_PDI_TYPE_PENDING(
            "PROJECT TEAM NOTIFY > AMISP PDI TYPE PENDING"),
    PROJECT_TEAM_PROJECT_TEAM_READY_FOR_DISPATCH(
            "PROJECT TEAM > PROJECT TEAM READY FOR DISPATCH"),
    PROJECT_TEAM_SCM_READY_FOR_DISPATCH(
            "PROJECT TEAM > SCM READY FOR DISPATCH"),
    PROJECT_TEAM_NOTIFY_SCM_LOCATION_DETAILS(
            "PROJECT TEAM > NOTIFY SCM LOCATION DETAILS"),


    // FINANCE
    FINANCE_APPROVED_SCM_PENDING(
            "FINANCE APPROVED > SCM PENDING"),
    FINANCE_TEAM_REJECTED(
            "FINANCE TEAM REJECTED"),
    FINANCE_SCM_PLAN_TO_DISPATCH(
            "FINANCE > SCM PLAN TO DISPATCH"),
    FINANCE_CLOSURE_DONE_SCM_CLOSURE_PENDING(
            "FINANCE CLOSURE DONE > SCM CLOSURE PENDING"),

    // SCM
    SCM_FINANCE_POST_APPROVAL_PENDING(
            "SCM > FINANCE POST APPROVAL PENDING"),
    SCM_CREATED_TICKET_CLOUD_PENDING(
            "SCM CREATED TICKET > CLOUD PENDING"),
    SCM_JIRA_TICKET_CLOSURE_SYRMA_PENDING(
            "SCM JIRA TICKET CLOSURE > SYRMA PENDING"),
    SCM_NOTIFY_RMA_QC_PENDING(
            "SCM NOTIFY > RMA QC PENDING"),
    SCM_NOTIFY_PROJECT_TEAM_BUILD_IS_READY(
            "SCM NOTIFY > PROJECT TEAM BUILD IS READY"),
    SCM_NOTIFY_AMISP_READY_FOR_DISPATCH(
            "SCM NOTIFY > AMISP READY FOR DISPATCH"),
    SCM_LOGISTIC_PENDING(
            "SCM > LOGISTIC PENDING"),
    COMPLETED(
            "COMPLETED"),

    // CLOUD
    CLOUD_CREATED_CERTIFICATE_SCM_PROD_BACK_CREATION_PENDING(
            "CLOUD CREATED CERTIFICATE > SCM PROD-BACK CREATION PENDING"),

    // SYRMA
    SYRMA_PROD_TEST_DONE_SCM_ACTION_PENDING(
            "SYRMA PROD/TEST DONE > SCM ACTION PENDING"),
    SYRMA_RE_PROD_TEST_DONE_SCM_ACTION_PENDING(
            "SYRMA RE-PROD/TEST DONE > SCM ACTION PENDING"),

    // RMA
    RMA_QC_PASS_SCM_ORDER_RELEASE_PENDING(
            "RMA QC PASS > SCM ORDER RELEASE PENDING"),
    RMA_QC_FAIL_SYRMA_RE_PROD_TEST_PENDING(
            "RMA QC FAIL > SYRMA RE-PROD/TEST PENDING"),

    // LOGISTIC
    LOGISTIC_FINANCE_CLOSURE_PENDING
            ("LOGISTIC > FINANCE CLOSURE PENDING"),
    DELIVERY_PENDING(
            "DELIVERY PENDING"),
    PDI_PENDING(
            "PDI PENDING"),
    POST_PDI_FAIL_RETURN_AMISP(
            "POST PDI FAIL RETURN AMISP");

    private final String display;

    OrderStatus(String display)
    {
        this.display = display;
    }

    public String toDisplay()
    {
        return display;
    }
}
